- name: Install Nginx, MySQL, PHP and modules
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - nginx
    - mysql-server
    - mysql-client
    - php8.1-fpm
    - php8.1-mysql
    - python3-pymysql

- name: Start and enable Nginx and MySQL
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nginx
    - mysql

- name: Sets the root password
  mysql_user:
    name: "{{ mysql_db_user }}"
    password: "{{ mysql_db_password }}"
    config_file: /etc/mysql/debian.cnf

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    config_file: /etc/mysql/debian.cnf

- name: Removes the MySQL test database
  mysql_db:
    name: test
    state: absent
    config_file: /etc/mysql/debian.cnf

- name: Configure Nginx for PHP
  copy:
    src: nginx_default
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx

- name: Configure index.php
  template:
    src: templates/index.php.j2
    dest: /var/www/html/index.php

- name: Open Nginx port
  ufw:
    rule: allow
    port: 80
